version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: ./backend
    container_name: stock-api-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_PAPER=${ALPACA_PAPER:-true}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    restart: unless-stopped
    # Use this for development to enable hot-reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    container_name: stock-app-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - backend
    # Use this for development to enable hot-reloading
    command: npm start

  # Nginx for production (commented out for development)
  # nginx:
  #   build: ./nginx
  #   container_name: stock-app-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   restart: unless-stopped

networks:
  default:
    name: stock-analysis-network